language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
- python --version
- pip install -U pip
- export PYTHONPATH=$PYTHONPATH:$(pwd)/python
- apt-get install libproj-dev proj-data proj-bin
- apt-get install libgeos-dev
install:
  - pip install -r ./python/requirements.txt
script:
  - python -m unittest python/test/test_visible.py
