language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PROJINST=$HOME/gdalinstall
    - PROJBUILD=$HOME/projbuild
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal
jobs:
  include:
    - python: "3.7"
      env: GDALVERSION="2.2.2" PROJVERSION="6.1.1"

before_install:
  - python --version
  - pip install -U pip
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/python
  - sudo apt-get update
  - sudo apt-get install libproj-dev proj-data proj-bin
  - sudo apt-get install libgeos-dev
  - sudo apt-get install libgdal-dev
  - which gdal-config
  - gdal-config --version


install:
  - pip install GDAL==2.2.2
  - pip install -r ./python/requirements.txt
script:
  - python -m unittest python/test/test_visible.py
