language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
- python --version
- pip install -U pip
- export PYTHONPATH=$PYTHONPATH:$(pwd)/python
- sudo apt-get update
- sudo apt-get install libproj-dev proj-data proj-bin
- sudo apt-get install -y gdal-bin 
- export CPLUS_INCLUDE_PATH=/usr/include/gdal
- export C_INCLUDE_PATH=/usr/include/gdal
- sudo apt-get install libgeos-dev
- sudo apt-get install libgdal-dev
install:
  - pip install -r ./python/requirements.txt
script:
  - python -m unittest python/test/test_visible.py
