language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PROJINST=$HOME/gdalinstall
    - PROJBUILD=$HOME/projbuild

jobs:
  include:
    - python: "3.7"
      env: GDALVERSION="3.0.1" PROJVERSION="6.1.1"

before_install:
  - python --version
  - pip install -U pip
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/python
  - sudo apt-get update

install:
  - pip install -r ./python/requirements.txt
script:
  - python -m unittest python/test/test_visible.py
