language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
- python --version
- pip install -U pip
- export PYTHONPATH=$PYTHONPATH:$(pwd)/
install:
  - pip install -r requirements.txt
script:
  - python -m unittest python/test/test_visible.py
